version: "3"
services:
  minecraft-server:
    build:
      context: "./image"
    environment:
      - "VERSION=1.20.4"
      - "EULA=true"
      - "FORCE_UPDATE=false"
      - "JAVA_XMX=1G"
      - "JAVA_XMS=1G"
#      - "JAVA_OPTIONS="
# Default: -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Dusing.aikars.flags=mcflags.emc.gs
    ports:
      - "25565:25565"
      - "8123:8123"
    volumes:
      - "./data:/data"
    restart: always
    stdin_open: true
    tty: true
    stop_signal: SIGINT
  db:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=abnfouaerofa"
    volumes:
      - "./db:/var/lib/mysql"
